### ISSUE TITLE
Check Point 1 : Ready

### ISSUE THREAD

**Issue by alisamoua** [mad-java-ent-f20/indieProject#1]
Hi @pawaitemadisoncollege 

Can you check my "check point 1" to see if there is anything you would like me to add or change?!

Thanks!

**Comment by pawaitemadisoncollege** [comment]
This is looking really good @alisamoua !  

- [x] Comparing your user stories to the project objectives for the course, I think a delete scenario is missing. Is there  a user story that involves delete that you could add?
- [x] There's reference to an admin role in the readme.md, what things should the admin be able to do? These should also be in the user story list.
- [ ] You have some things in your screen design and flow for photos, notes, a budget, and the user profile. Should those be user stories too? Or maybe some are stretch goals (non-MVP)? Either way, they should be listed in the user stories, and identified as MVP or stretch goals/non-MVP.
- [ ] Project plan - remove any google maps/snow depth stuff/anything else that doesn't pertain to your project. Or maybe you were planning to use google maps?
- [ ] We should start thinking about a good api/service to use in your project. This could be something like the JavaMail API to send emails to guests or the admin or whoever you like (add a user story for this).  Or maybe there's a web service out there that is wedding related that could be helpful. Here are a few that might be good to get some ideas flowing: https://www.programmableweb.com/category/weddings
