### ISSUE TITLE
peer review - angel

### ISSUE THREAD

**Issue by cruzang000** [mad-java-ent-f20/indieProject#4]
Hey Alisa, attached is my peer review for your project!

[alisaPeerReview.txt](https://github.com/mad-java-ent-f20/Init-to-Commit-Wedding-Planner/files/5351777/alisaPeerReview.txt)

**Comment by pawaitemadisoncollege** [comment]
@cruzang000 and @alisamoua One code review item was using logging over printlns - I snuck some in there with that Database class (this also shows how to search an entire repository for some text like `print` : 

![Screen Shot 2020-10-09 at 9 00 12 AM (2)](https://user-images.githubusercontent.com/13874466/95592281-0551d100-0a0e-11eb-9d15-facbcde75369.png)
